### ISSUE TITLE
iOS and Android inconsistent behaviour

### ISSUE THREAD

**Issue by zeromaro** [csdcorp/speech_to_text#102]
Hello, first of all, thank you so much for such an amazing plugin! It really rocks!

However, I've discovered a potential bug. On iOS everything works as expected - once I start speech recognition, it records. Once I stop - it stops.

For Android - it's different. Once I start - it starts to recording and it will finish within 5 seconds, if nothing is said. After finish, it's not possible to `listen()` again.
Also, on iOS by default no sounds are playing, but for Android - it does. Also `cancel()` and then immediately `listen()` for iOS works well, but for Android it seldom doesn't work and `listen()` is not executed.

Is this inconsistency expected?

**Comment by sowens-csd** [comment]
Thanks for the positive feedback, great to hear. 

The only issue on your list that I'm currently tracking is that cancel / stop on Android don't seem to work on some devices. That's being tracked on #69 if you want to watch it. There appears to be an open issue on Android about this problem. It only seems to affect some devices so I haven't been able to reproduce it. What device and Android version are you using? Have you seen it on multiple devices? 

It definitely should be possible to listen multiple times. What version of the plugin and Android are you seeing that behaviour on? Do you get an error or it just doesn't recognize any speech? 

There's a flag you can set on the `initialize` method, `debugLogging`, could you set that to true and then capture the logs from a device where you're seeing the problem and put them in this thread? 

The sounds difference is expected. On Android the OS plays sounds when listening starts/stops. iOS does not do this. The plugin does have the ability to play sounds on iOS to make the behaviour more similar but you have to supply your own sounds. The example application shows how to do this.

**Comment by zeromaro** [comment]
Thank you for your prompt reply, Stephen. I've created empty project for you to check it out.

1. Open the app;
2. Click Start;
3. Don;t say anything for 5 s.


iOS will continue listening, Android will stop with error.
```
I/flutter (24706): Error: SpeechRecognitionError msg: error_speech_timeout, permanent: true
```

Im using OnePlus 6 with Android 10.

**Comment by sowens-csd** [comment]
I haven’t tried your example yet but I did have a look. Two things to try. First set `partialResults` true on the listen call to see if you are getting any results the second time. Second change your cancel to stop. Cancel doesn’t return the current result, it just cancels the listen with no results while stop should give you whatever result it has as the final result.

**Comment by sowens-csd** [comment]
Any update on this?

**Comment by zeromaro** [comment]
Hello Stephen,

None of your proposed suggestions didn't solve Android issue:
```
Open the app;
Click Start;
Don't say anything for 5 s.
iOS will continue listening, Android will stop with error.
```
`I/flutter (24706): Error: SpeechRecognitionError msg: error_speech_timeout, permanent: true`

**Comment by sowens-csd** [comment]
Yes, I should have said. Android does have a shorter timeout than iOS so that timeout error that you're seeing is expected. There doesn't appear to be any way to change that timeout though I've been trying and have another issue open to look at possible work arounds. For now however, that is expected behaviour. 

The suggestions I made were to address your other issue that you were unable to start a new listen session after the timeout.

**Comment by zeromaro** [comment]
Oh wow, that's extremely unfortunate. 5s timeout delay and force stop is something we might not afford and might need to look for other libs to integrate. Sad to hear that. I'll need to check how could I solve it with least `hack-code`. :)

>The suggestions I made were to address your other issue that you were unable to start a new listen session after the timeout.
To be more precise - once timeout happens and user clicks on `start` - it won't work. However, if user clicks on `stop` and then `start` - it will work well. That'd be a workaround, to have this logic, if user experience `error_speech_timeout` exception. (That might be a quick solution?).

**Comment by sowens-csd** [comment]
Yes, I understand that's a problem for many use cases. I wish Android supported the behaviour better. This is the issue where people are discussing it in case there's anything useful there. #63 

There are two possible solutions to your issue of handling the timeout error. The simplest is to use the `cancelOnError` property of the `listen` method. That will automatically stop the current listen on any permanent error. An alternative is to call `stop` in your error handler. 

I'm not sure what the problem is from your description above. You say 'since status is listening - nothing happens'. The status looks right to me so there must be something I'm not understanding from your description.

**Comment by D0KKAEl3I** [comment]
****
