### ISSUE TITLE
Unable to make CupertinoPicker work instead of the DropdownButton

### ISSUE THREAD

**Issue by tedserdel** [csdcorp/speech_to_text#103]
Following the Example, I have tried implementing the CupertinoPicker using the code snippet below, with no success. Please advise...

`
//...

  List<String> _preferredLocaleIds = ['en_US', 'es-ES',];

  CupertinoPicker iOSPicker() {
    List<Text> pickerItems = [];
    for (String locale in _preferredLocaleIds) {
      pickerItems.add(Text(locale));
    }

    return CupertinoPicker(
      backgroundColor: Colors.white,
      itemExtent: 24.0,
      onSelectedItemChanged: (selectedIndex) {
        print(selectedIndex);
        setState(() {
          _currentLocaleId = _preferredLocaleIds[selectedIndex];
        });
      },
      children: pickerItems,
    );
  }`

**Comment by sowens-csd** [comment]
You don't say what the problem is but this doesn't look like a problem about the speech_to_text plugin. If it is related to the plugin please provide more details. 

If it is a general Flutter question then you'd be better off asking in [SO](https://stackoverflow.com) or any of the [ Flutter community support options](https://flutter.dev/community).

**Comment by tedserdel** [comment]
Hello Mr. Owens, you can delete this issue since it is not particularly about the speech_to_text plugin.

I did get it to work! 😁

**Comment by tedserdel** [comment]
Hello Mr. Owens, you can delete this issue since it is not particularly about the speech_to_text plugin.

I did get it to work! 😁
