### ISSUE TITLE
not work with kotlin  3 

### ISSUE THREAD

**Issue by niypoo** [csdcorp/speech_to_text#14]
after install in_app_purchase that depends on kotlin 3 I have facing issue with build so I remove speech_to_text and try install it again , now I can't

```
So, because stok_app_a depends on both speech_to_text ^0.6.3 and in_app_purchase ^0.2.2+4, version solving failed.
pub get failed (1; So, because stok_app_a depends on both speech_to_text ^0.6.3 and in_app_purchase ^0.2.2+4, version solving failed.)
```

**Comment by niypoo** [comment]
I have updated to version 0.7 but same issue 
`pub get failed (1; So, because stok_app_a depends on both speech_to_text ^0.7.0 and in_app_purchase ^0.2.2+4, version solving failed.)`

**Comment by niypoo** [comment]
I have sol

**Comment by sowens-csd** [comment]
Glad to hear your issue was resolved. Anything I should add to the documentation to help others avoid the issue?

**Comment by niypoo** [comment]
first thanks you for this great work , 
I have faced issue with another package you can see the issue here with how i avoid it 
https://stackoverflow.com/questions/59467251/version-solving-failed-when-try-get-pubspec-yaml

**Comment by sowens-csd** [comment]
Thanks for the reference, that explains it, and may well help others. I'll add it to the docs for the next release. 

I'm surprised the Flutter team haven't updated their own plugin to the latest dependency. There's an open issue for it here https://github.com/flutter/flutter/issues/43084, I just upvoted it. Notice on the https://pub.dev/packages/in_app_purchase#-analysis-tab- that it reports the json_annotation support as a problem. It gave my plugin the same report which is why I upgraded.
