### ISSUE TITLE
SpeechRecognitionResult.finalResult taking too long to return when listen on iOS

### ISSUE THREAD

**Issue by itsmejohndoe** [csdcorp/speech_to_text#142]
Hey guys!

The plugin works great on Android but on iOS running iOS 12 and 13 the listen callback is taking too long to receive a call with finalResult == true after stop talking.

Any clues on what is causing this? Anyone has experienced something similar?

Thanks in advance!

**Comment by sowens-csd** [comment]
Thanks for the feedback. 
I have an idea on the possible cause, but it depends on how long a delay you are seeing. For some reason on iOS there is an issue getting final results == true from the OS. Because of that I now create a true result based on the last intermediate result if none is received from the OS within a defined time. The delay is to ensure that a 'real' final result has time to come in from the OS before the generated result is created. The current delay is 100 ms.  If that's the delay you're seeing then that is likely the cause, if it is longer than that then I'd like some more information.

I am still trying to figure out why I'm no longer reliably getting final results from the OS, but this workaround at least provides reliable behaviour to the plugin users in the meantime. I admit it's not idea.
