### ISSUE TITLE
Fatal Exception: java.lang.SecurityException Not allowed to bind to service Intent

### ISSUE THREAD

**Issue by hsangtini** [csdcorp/speech_to_text#148]
Hi,

I'm getting this error at Firebase Crashlytics.

```
Fatal Exception: java.lang.SecurityException
Not allowed to bind to service Intent { act=android.speech.RecognitionService cmp=com.screenple.screenple/.ScreenpleService }
android.app.ContextImpl.bindServiceCommon (ContextImpl.java:1460)
android.speech.SpeechRecognizer.startListening (SpeechRecognizer.java:288)
com.csdcorp.speech_to_text.SpeechToTextPlugin$startListening$1.run (SpeechToTextPlugin.kt:268)
android.os.Handler.handleCallback (Handler.java:739)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
```

**Comment by sowens-csd** [comment]
What Android version and device was this on? Some of the references I've seen on that error have mentioned services. Is the plugin being used in a full app or in a service?

**Comment by hsangtini** [comment]
There are screen short from Firebase Crashlytics. I am using for full app.

![screenshot_166](https://user-images.githubusercontent.com/13326277/98798578-9ae2e500-2440-11eb-8580-6dd962dc2676.png)

**Comment by sowens-csd** [comment]
Can you reproduce the problem on a test device? I haven't been able to but there could be some combination I'm missing that's present in your app. Does your app use any other plugins which might also try to use the microphone? 

This thread actually looks quite promising, especially since if this is the problem your users could probably resolve the issue themselves without a code change:

https://stackoverflow.com/questions/25250761/speech-recognizer-on-htc-one-m7

Please let me know if this helps.

**Comment by hsangtini** [comment]
Thanks @sowens-csd 

Thanks for helps.
