### ISSUE TITLE
iOS listening

### ISSUE THREAD

**Issue by sbolognini** [csdcorp/speech_to_text#165]
Hi,
I noticed two different behaviours in how the listening process happens in iOS and Android.
While in Android the recognized results are served continuously while the listening process is active, on iOS I have to stop the listening or wait the listenFor to expire before having the results (that in this case are related to the entire listening process).
Is that a known behaviour or am I missing something?

Thanks

**Comment by sowens-csd** [comment]
No, there should be no difference between the platforms on this point. Can you post a code snippet for the `listen` method. The only thing that should influence that is the value of the `partialResults` parameter, which should be true to get intermediate results. But that should affect either platform in the same way.

**Comment by sagaracharya24** [comment]
I am also facing the same issue, here is my repo i have created a sample application in which for android it works fine but for the ios it does not respond if the stop is triggered in the ui.
This is the repo : https://github.com/sagaracharya24/VoiceApp

**Comment by sowens-csd** [comment]
You say 'it does not respond if the stop(recognition) is triggered in the ui'. Can you give me more detail on what you expect to happen and what does happen? I had a quick look at your repo and I don't see anything obviously wrong. This doesn't sound like the same problem described in the original issue of not getting intermediate results but perhaps I'm not understanding the issue. 

I just ran the example app on iOS and `stop` does what I expect it to do, which is to deliver final results.

**Comment by sagaracharya24** [comment]
So what i am trying to achieve is when the user hit's the button to speak the  recognition starts and I say few words but the problem is the recognition complete handler gets called after 30 or 45 seconds, till then the ui just show its in the recognising state. I will just add the video link of what i am trying to achieve and what's happening
In the video i have two commands In which the first command i say the words and then i hit the stop button so it responds quickly. And the second command i speak i do not hit any button the result completion handler responds after 45 seconds which is wrong. just check the link
This is the video link:
 https://drive.google.com/file/d/1V9rqwhpdS5F1APJq7-OBkKlz4zmwmQkQ/view?usp=sharing

**Comment by sagaracharya24** [comment]
And @sowens-csd I was also checking for the sample example that you provided in which i removed listenfor and made same changes in  the following code  like i should only get the text if the recognition is complete, so this one responds me the data after 30 seconds. 
  void resultListener(SpeechRecognitionResult result) {
    setState(() {
      if (result.finalResult) {
        lastWords = "${result.recognizedWords}";
      }
    });
  }
  
  then the same behaviour is being reproducethat i mentioned above

**Comment by sowens-csd** [comment]
You are checking the `result.finalResult` status in that method. That status will only be true after recognition is complete, which is either when `stop` is called or the recognizer completes based on time. If you try it without that does it behave more like what you were expecting?

**Comment by sowens-csd** [comment]
Any update on this?
