### ISSUE TITLE
finalTimeout property doesn't work

### ISSUE THREAD

**Issue by singhmanav001** [csdcorp/speech_to_text#235]
"finalTimeout" does not change while using it, it always considers the default value as 2secs. Please help, how to increase the timeout when initializing speech recognition.

**Comment by SreehariRajeev** [comment]
Try to change it directly from the speech_to_text.dart file.

**Comment by sowens-csd** [comment]
I'm not sure what the issue is, could you provide a code sample showing what's going wrong? There is a `finalTimeout` parameter to the `initialize` method but not a property. Initialize should only be called once so you can only set the values once per program execution. That parameter is only used to determine when to automatically create a final recognition value if the platform doesn't provide one. Are you saying that even if you set it to a higher value on first initialization that the new value is not being used?

**Comment by singhmanav001** [comment]
> I'm not sure what the issue is, could you provide a code sample showing what's going wrong? There is a `finalTimeout` parameter to the `initialize` method but not a property. Initialize should only be called once so you can only set the values once per program execution. That parameter is only used to determine when to automatically create a final recognition value if the platform doesn't provide one. Are you saying that even if you set it to a higher value on first initialization that the new value is not being used?

Yes @sowens-csd whenever I put the new value, it doesn't take that.

**Comment by sowens-csd** [comment]
How can you tell it is not taking the value you give it? What behaviour are you seeing and how can I reproduce it?

**Comment by sowens-csd** [comment]
Closing this issue because I don't have enough information to troubleshoot.
