### ISSUE TITLE
Possible to have multiple instances running?

### ISSUE THREAD

**Issue by AlexHartford** [csdcorp/speech_to_text#236]
Sort of related to https://github.com/csdcorp/speech_to_text/issues/63.

Trying to have an application that wakes up when a specific word is spoken. My [demo](https://github.com/AlexHartford/voice_control_ui/blob/master/packages/voice_control_ui/lib/speech.dart) sort of works, but the main issue is the timeouts can cause part of speech to be missed.

I believe a potential solution would be to have one listener always seeking the wake word, which would trigger another to start, which would end up actually handling what the user wants to say.

This would likely still have a few misses, but it'd be a lot less noticeable, and would only appear in a way that is common to voice assistants (Hey Google.... _Hey Google..._ _**HEY GOOGLE!!!!**_).

I am not entirely sure if this is possible, but if it is, I would be happy to contribute to whatever needs to happen to add this capability.

**Comment by sowens-csd** [comment]
You can't have multiple instance because the microphone can only be owned by one instance at a time, at least for speech recognition. Currently the only way to get close to this behaviour is to chain them, wait for the not listening status and start a new listening state. That does still leave gaps where words can be missed.

**Comment by AlexHartford** [comment]
Okay, I figured as much. Thanks for the suggestion, I'll see if I can improve my solution with i t.
