### ISSUE TITLE
Extend README - Not working for Brave Browser nad Firefox (Linux)

### ISSUE THREAD

**Issue by JulianKowalczuk** [csdcorp/speech_to_text#239]
Brave Browser is built on top of Chromium. It should works same way I guess. But it doesnt.

While trying to listen for result, I get error:
```SpeechRecognitionError msg: network, permanent: false```

It happens because of:
https://community.brave.com/t/microphone-is-not-working-in-brave-browser/183787

For now I think its good to mention about some browser usage exceptions for this package

**Comment by sowens-csd** [comment]
Looks like this is a known issue with Brave and there is no fix planned that I could see. 

https://github.com/brave/brave-browser/issues/3725

**Comment by JulianKowalczuk** [comment]
Damn, I've just edited issue with info, since I decided to visit Windows distro to check it.

Seems like SpeechRecognition Web API is broken, because I have no issues with using mic in online meetings.
But its nice it works great on Android devices (main client targets).

**Comment by sowens-csd** [comment]
It's a good thought to add to the README, I'll do that.

**Comment by Shivam-dev925** [comment]
hii,
i implemented it on flutter mobile and web in mobile it is working good but on web it is not.
**BEHAVIOUR**=>
 i added the listener here 
  await _speechToText.listen(
          onResult: _onSpeechResult,
          listenMode: ListenMode.deviceDefault,
        );
and _onSpeechResult function is 
  void _onSpeechResult(SpeechRecognitionResult result) {
 
    try {
      if (result.finalResult) {
        assistantController.conversation.value += result.recognizedWords;
      }
    } catch (e) {
      print("exception in recognizition ===> $e");
    }
  }
  when i stops talking then it is not giving me finalWords equal true and that's why the transcripted text is not coming 
  please take a look to this
