### ISSUE TITLE
pauseFor is not working on Android.

### ISSUE THREAD

**Issue by prabhunath111** [csdcorp/speech_to_text#286]
Can anybody help me , pauseFor is not working in android device

```
  void _startListening() async {
    await _speechToText.listen(
        onResult: _onSpeechResult,
        localeId: GetStorage().read(speechLangCode) ?? 'en_IN'
        , listenFor: Duration(seconds: 30),
        pauseFor: Duration(seconds: 5),
        partialResults: true,
        cancelOnError: true,
        listenMode: stt.ListenMode.confirmation);
    setState(() {});
  }
```

**Comment by sowens-csd** [comment]
Unfortunately Android has a short pause value built into the OS and it can't be changed. As a result the `pauseFor` parameter is of limited use on Android. I added it so that iOS could be made to behave in a somewhat similar fashion to Android. One way to think about is that regardless of the phone defaults it will not allow a pause of any longer than the value given in the `pauseFor` value.
