### ISSUE TITLE
Confidence rating on phrases

### ISSUE THREAD

**Issue by CodyBontecou** [csdcorp/speech_to_text#289]
When providing "Hello World" as a spoken phrase, I cannot get the package to get any higher than an 84% confidence level.

Is it possible to adjust the confidence levels and/or expectations for the package to expect phrases rather than words? 

Can I provide the phrase beforehand so that package can place a degree of preference for certain words or phrases as well as increase the confidence level?

These are the results when I print `result.confidence` during the `_onSpeechResult` method:
```
[ 
  SpeechRecognitionWords words: hello world,  confidence: 0.8361229, 
  SpeechRecognitionWords words: helloworld,  confidence: 0.8311545, 
  SpeechRecognitionWords words: hello wrld,  confidence: 0.8751238, 
  SpeechRecognitionWords words: Halo world,  confidence: 0.7769877
]
```
It's odd `hello wrld` has a higher confidence level. I'm also unsure of why `hello world` is what `print(result.recognizedWords)` prints out even though it has a lower confidence level.

**Comment by sowens-csd** [comment]
You can somewhat tune the recognition by using the `listenMode` parameter on the `listen` method. Phrases are most likely going to be best recognized by the `ListenMode.dictation` mode. You can't alter the confidence. On iOS there is a way to add phrases but I don't yet support it in the plugin, I'm not sure if similar behaviour is supported on Android but I haven't found it yet if so. On iOS adding phrases is supposed to be for words that are specific to your app, like character names or other non-words that wouldn't otherwise be recognized. I don't know whether adding real words to the list would help or not. Of course that is also something I could do in the plugin itself, if provided with a list of preferred words then I could filter recognized words on that basis so they are always the top result if they are in the list. That's an interesting feature idea. 

Interesting find on `recognizedWords`, I just checked the implementation and that property is always the first item in the list of recognized words regardless of confidence. I should probably change that to reflect the highest confidence instead.

**Comment by CodyBontecou** [comment]
Hmm, interesting. `ListenMode.dictation` didn't seem to change the accuracy of the confidence. How would I go about using ListenMode.search? Do I pass it something?

**Comment by sowens-csd** [comment]
No, it just causes some change to the recognition engine's bias that should make it work better for recognizing search requests. I'm guessing that search terms are less often complete phrases but the docs are somewhat vague.

**Comment by CodyBontecou** [comment]
Ah, okay. Thank you for the explanations!
