### ISSUE TITLE
Duration Issue 

### ISSUE THREAD

**Issue by rajvaya** [csdcorp/speech_to_text#30]
i want use Listener for 5 minutes  even after setting the listenFor Duration it stops listening can you help me with this

**Comment by sowens-csd** [comment]
Is this on iOS or Android? Android is pretty aggressive in stopping listening if the speaker pauses. I'll look again at the docs, maybe there's some control I can exert. Right now the best approach is to restart the listener when it stops but I realize that's not a great answer.

**Comment by rajvaya** [comment]
It's on android but how Google assistant is able to listen actively I am trying to achieve that in my app

**Comment by sowens-csd** [comment]
This plugin isn't designed for that. 

Just my opinion but if I were looking to add that kind of functionality into an app I'd look at working with Google Assistant or Siri by adding extensions / plugins to them rather than trying to have the app listen all the time. Here's a link for Android https://developers.google.com/assistant I don't know if there are plugins in this area yet.

**Comment by rajvaya** [comment]
thanks for helping me but try to fix ListenFor thing it will help me alot anything else i can contribute then let me know

**Comment by sowens-csd** [comment]
Not the design goal of this plugin.
