### ISSUE TITLE
onStatus method continuously shows "done" and "notListening" status  even in silence mode and crashes the app in IOS

### ISSUE THREAD

**Issue by basnetjiten** [csdcorp/speech_to_text#342]
I have tried restarting the listener if the status is notListening or done, but It continuously prints  "done" and "notListening status. How can we be sure that it has recognized the speech and the status is "done" properly?

       void statusListener(String status) async {
           if ('notListening' == status || 'done' == status) {
          print('onStatus(): $status ');
     
         Timer(const Duration(milliseconds: 100), () {
           _initSpeech();
            startSTTListening();
         });
           // await Future.delayed(const Duration(milliseconds: 50)).then((value) => startSTTListening());
         }
      }

**Comment by sowens-csd** [comment]
Looks like you're probably trying to implement continuous listening? There is a lengthy issue #253 which has a discussion of the issues and some code samples / recommendations. 

As a general rule I don't recommend it because the platforms are not really designed for this use but I understand that each app is unique and you may well have use cases that require it.
