### ISSUE TITLE
error_listen_failed on ios Simulator

### ISSUE THREAD

**Issue by yildirimbhdr** [csdcorp/speech_to_text#427]
When ı run ios simulator (İphone 14)I  got error_listen_failed. Works on normal devices and ı installed spoken contents on ios simulator. 
So this is my full error log

```
023-08-21 02:04:39.215841+0300 Runner[79246:4490621] flutter: \^[[38;5;196m│ ⛔ {<…>
2023-08-21 02:04:39.215894+0300 Runner[79246:4490621] flutter: \^[[38;5;196m│ ⛔   "errorMsg": "error_listen_failed",<…>
2023-08-21 02:04:39.215939+0300 Runner[79246:4490621] flutter: \^[[38;5;196m│ ⛔   "permanent": true<…>
2023-08-21 02:04:39.215984+0300 Runner[79246:4490621] flutter: \^[[38;5;196m│ ⛔ }<…>
```

My flutter version : 3.10.4
I hope you can help me solve the problem

**Comment by sowens-csd** [comment]
I have consistently had problems with simulators. In general I don't bother trying to test sound recognition on them because it's more of a hassle than it's worth. 

One thing you could check is that your simulator is capturing the device microphone. There's an option on the I/O menu of the simulator to set where the input comes from. I have sometimes had luck changing that.

**Comment by yildirimbhdr** [comment]
Okey
