### ISSUE TITLE
Haptic feedback does not work when recording

### ISSUE THREAD

**Issue by bbader-kada** [csdcorp/speech_to_text#465]
Hello!

First of all, thank you for developing this fantastic package!

I came across an issue, like when I am listening to a SpeechToText recorder, the haptic feedbacks are not triggered.

Tested on real device: IOS 16.5, Iphone 13.
<img width="621" alt="Screenshot 2023-12-03 at 20 21 50" src="https://github.com/csdcorp/speech_to_text/assets/105285715/5b76a51d-60cb-4b3f-b634-1ea5052bf9e7">

**Comment by sowens-csd** [comment]
Are you using the HapticFeedback Dart class or a plugin? Does it stop working as soon as you initialize or only while a `listen` is active?

**Comment by bbader-kada** [comment]
The dart class. And after initialize.

**Comment by sowens-csd** [comment]
Turns out this is a known issue, with a possible resolution. Apple disables haptic feedback while the microphone is captured to prevent the haptics from interfering with speech recognition or other audio capture. There is a way to override this but I'm not sure whether it's a good idea in general. 

How do you feel about the trade off between better audio quality and being able to trigger haptics? 

https://stackoverflow.com/questions/44582128/how-can-i-play-a-haptic-feedback-while-avcapture-session-is-running

**Comment by bbader-kada** [comment]
I think it depends on the use case. In my for example, there is no way that user would use the speech recognition and receive haptic feedback at the same time. But I agree that in many cases it could lead to degradation in sound quality.

What about an option at initialization, to let everybody decide how would they like to do so based on their usage?

**Comment by bbader-kada** [comment]
No sorry. I meant no matter what, it is disabled. So I have a listen section as well, but there I cannot user haptic also. So for for me the perfect would be the option to enable the haptics while listening

**Comment by sowens-csd** [comment]
I just tried this on an iPhone Xs running iOS 16.7.1 and Haptics seems to work after initialize. The only time it does not work is when STT is actively listening. I tested this by adding a button in the example app that triggers a `HapticFeedback.heavyImpact()` call. I can feel the haptics before initialize, after initialize and after stopping a listen. I cannot feel haptics after clicking listen and before clicking stop. 

I don't think that's the same behaviour that you're seeing? I think you were saying that haptics never works after STT has been initialized?

**Comment by bbader-kada** [comment]
Yes I am sorry, you are right. I dont know what happened back then. So yes, I cannot access haptic feedback only while there is an active listening. After just simply initilaize it works

**Comment by sowens-csd** [comment]
There is a new version in pub.dev now, 6.6.0-dev which supports an option to enable haptics on iOS during recognition. I've changed the `listen` method to optionally use a`listenOptions` parameter instead of other individual parameters for the options. It is a `SpeechListenOptions` type which has `enableHaptics` as an available option. So it would look like this:

```dart
    final options = SpeechListenOptions(
        onDevice: _onDevice,
        listenMode: ListenMode.confirmation,
        cancelOnError: true,
        partialResults: true,
        autoPunctuation: true,
        enableHapticFeedback: true);
    speech.listen(
      onResult: resultListener,
      listenFor: Duration(seconds: listenFor ?? 30),
      pauseFor: Duration(seconds: pauseFor ?? 3),
      localeId: _currentLocaleId,
      onSoundLevelChange: soundLevelListener,
      listenOptions: options,
    );
```

Please let me know if you have a chance to try it.

**Comment by bbader-kada** [comment]
I tested it out, it works perfectly! Thank you so much again!
