### ISSUE TITLE
Audio Turned Off After Using STT with Flutter WebRTC

### ISSUE THREAD

**Issue by emrecodeway** [csdcorp/speech_to_text#479]
### Description
I am developing a Flutter application where I use both the `speech_to_text` package for speech recognition and `flutter_webrtc` for video streaming. The application functions correctly with the WebRTC video streaming, including audio, until speech recognition is initiated. After using the `startListening` (and `startListeningiOS` for iOS) method from the `speech_to_text` package, the speech is successfully recognized and processed. However, once the STT session is stopped (using `stopListeningiOS`), the audio from the WebRTC stream is turned off, and I'm unable to re-enable it.

### Steps to Reproduce
1. Start the application with WebRTC streaming, audio and video are working fine.
2. Initiate STT session with `startListening`/`startListeningiOS`.
3. Fetch the speech text and process it.
4. Stop the STT session with `stopListeningiOS`.
5. The WebRTC video continues to play, but the audio is turned off.

### Expected Behavior
After the STT session is stopped, the audio from the WebRTC stream should continue to play as normal.

### Actual Behavior
The audio from the WebRTC stream is turned off after the STT session is completed and does not resume.

### Additional Information
- `speech_to_text` package version: 6.5.1
- `flutter_webrtc` package version: 0.9.47
- Operating System: iOS

It seems like the STT functionality might be interfering with the WebRTC audio stream, and there doesn't appear to be a re-initialization or reactivation of the audio stream after the STT session is completed. I am looking for guidance on how to manage the WebRTC audio stream state in conjunction with the STT functionalities or if there's a known issue/workaround for this scenario.

Any assistance or insight into this issue would be greatly appreciated.

**Comment by emrecodeway** [comment]
Thank you for your response and clarification.

I would like to confirm that startListening and startListeningiOS are indeed custom methods in my implementation, inspired by the example code provided in the  package documentation. These methods function as expected.

However, the core issue I'm encountering is with the flutter_webrtc audio stream. Specifically, the audio gets muted after invoking the listen method from the package. This muting persists even after I execute the stop and cancel methods of the speech recognition package, before forwarding the recognized speech results to the streaming service.

On your suggestion, I will attempt to close the WebRTC session and then start a new one post-STT interaction, and I will observe that this approach does indeed resolve the audio issue. It seems like managing the WebRTC session state around the STT interactions is a viable workaround.

Thank you again for your assistance. It has been instrumental in helping me identify a solution.

**Comment by jpwire28** [comment]
PR #681 proposes an opt-in `SpeechListenOptions.preserveExistingAudioSession` option that addresses this — captures the pre-recognition category / options / mode, and when the pre-recognition category was `.playback` / `.playAndRecord` / `.multiRoute` (i.e. another subsystem's session was already active), restores that config on `stop` and leaves the session ACTIVE instead of deactivating it. Default `false` so existing callers see no change; opt-in for WebRTC / LiveKit coexistence.

35/35 platform-interface tests pass including two new ones for the channel wiring; Darwin behavior device-verified in a downstream production consumer (iPhone 15 / iOS 26.6.2, live LiveKit receive-only session, 5 mic turns + 1 post-idle reconnect turn, remote audio audible throughout).

Happy to iterate on shape.
