### ISSUE TITLE
OnDevice doesn’t work if wifi is turned off

### ISSUE THREAD

**Issue by muhammad-umair-khan** [csdcorp/speech_to_text#518]
I am testing on chrome and its working amazingly. The only problem is when i turn off device wifi with `OnDevice=true` it gives error. Why does onDevice need network. 

Also if there is some information how network is working. Is text sent through some backend api?

**Comment by sowens-csd** [comment]
For web support I believe they all use online web services but I don't know the details of the browser implementations of speech recognition. My implementation ignores the `onDevice` setting when targeting a web browser because the web API that I use has no support for requesting on device recognition.
