### ISSUE TITLE
  Aternates results always have confidence scores 0

### ISSUE THREAD

**Issue by RomanSoviak** [csdcorp/speech_to_text#54]

**Comment by sowens-csd** [comment]
What platform, OS version, and plugin version?

**Comment by RomanSoviak** [comment]
@sowens-csd both on Android and iOS. A version of the plugin is the last one.

**Comment by RomanSoviak** [comment]
@sowens-csd 
![image](https://user-images.githubusercontent.com/26696190/77681610-4583c180-6f9e-11ea-9ae4-e1e58813ce7f.png)

**Comment by sowens-csd** [comment]
Thanks, I'll have a look. I was just reviewing this as part of the duplicate callback issue and was seeing non-zero confidence values on Android in some cases. Perhaps there's a problem with the JSON conversion or something. I'll review.

**Comment by sowens-csd** [comment]
I've reviewed the confidence reporting and it looks like I'm passing back the results I receive from the speech recognition subsystem accurately on both iOS and Android. There are two complications. 

iOS - confidence scores seem to only be available after a final result. The final result is only available when you call stop. I'm considering a change to the next version of the lib to call Stop rather than Cancel from the `listenFor` timeout so that final results are more available in iOS. I think that would be a better implementation for other reasons as well. Even without this change you can see the confidence scores if you trigger the `stop` method after speaking. 

Android - the speech recognition subsystem seems to vary in the availability of the confidence scores. Sometimes the call contains a good set of confidence scores sometimes not. I think that's related to the fact that I receive duplicate results callback notifications. One of the notifications usually has the most usable data. How good the data is may depend on the particular device and OS version you're using. I haven't found a reliable way to always get good confidence scores from the OS.

**Comment by sowens-csd** [comment]
I'm going to close this. The confidence values aren't perfect but they do appear to be the best the platforms have to give.
