### ISSUE TITLE
Voice recognition improvment

### ISSUE THREAD

**Issue by MS893** [csdcorp/speech_to_text#574]
Hi,
It's not really an issue, but how can I improve the voice recognition ?
For example when I say in french "X-RAY", sometimes the result is "extrait" or "extrême", same for "Aix sol", it returns "et que ce sol" or "aixoll" or "ex sol",...
It should be great if there was a possibility to correct the recognition for future run (with a function that we can call and change the bad word with the good word).
I don't know if it's possible...
Thanks

**Comment by sowens-csd** [comment]
Unfortunately not through the plugin. Improvements to recognition have to happen on the platform since the plugin uses the native voice recognition of the platform. For example, on Android it is the native Android voice recognition system the plugin connects to so it would be Android that would have to improve its recognition. Like you, I wish it was better.

**Comment by MS893** [comment]
OK thanks for your answer. I will try to improve accepting some "bad words" (creating a set of words and verifying  that the bad word is or not in this set).
