### ISSUE TITLE
Not working in iOS

### ISSUE THREAD

**Issue by Ajit121** [csdcorp/speech_to_text#59]
I'm having few issues while running in simulator as well as in real devices
1) It's not asking for the permission in few real devices.
2) if  partialResults: false then its not returning result
3) if partialResults: true then result.finalResult is always false
4) listenFor: Duration(seconds: 10), not stopping in android

**Comment by sowens-csd** [comment]
What version of the plugin are you using? Are these issues consistent between Android and iOS? Is this with the example app or with an app that you're writing? What OS versions are you using?

**Comment by sowens-csd** [comment]
Do you have any more information for me?

**Comment by Ajit121** [comment]
I'm using the latest version. This is happening in iOS only and this is in
my application.

**Comment by sowens-csd** [comment]
Can you reproduce issues 1-4 in the example app on the same devices? 

For issue 4, what happens? You say it's 'not stopping'. Do you continue to receive result notifications after the timeout? The latest version, released this morning (2.1.0), changes the `listenFor` behaviour to `stop` instead of `cancel`. I'd be curious if the behaviour changed for you with that change. 

Note that permission can only be asked for once on a particular device. If it has been rejected previously then it will not ask again and you have to manually grant permission from settings.

**Comment by Ajit121** [comment]
1 and 4 seems to be working in the latest build but 2-3 still not working in iOS. but its working is android

**Comment by sowens-csd** [comment]
In previous versions using `listenFor` caused a cancel instead of a stop. As of 2.1 it uses stop which should give final results when it's done though I'm not positive I've tried that on iOS. Can you confirm that in all of 1-4 you are using `listenFor`? Can you see what happens if you call `stop` manually instead of allowing the timer to elapse?

**Comment by sowens-csd** [comment]
Any more information on this?
