### ISSUE TITLE
Interaction with the speaker

### ISSUE THREAD

**Issue by ab36245** [csdcorp/speech_to_text#66]
I've described my basic app in a previous issue (#65). As I mentioned there I have a second problem with my approach. When input is processed I produce an audio response using a text-to-speech package (flutter_tts).

This works ok but I've found that as soon as I generate audio output, speech_to_text (which is currently listening) will not recognize voice input until I've restarted it after the audio has completed.

I realize that interaction between microphone and speaker is potentially a tricky subject. Is there a "right way" to handle this? I guess I can just work out that the speaker is going to be used and restart the listening afterwards but I'm wondering if there might be a simpler solution?

Thanks again.

**Comment by sowens-csd** [comment]
There might be a solution to this but it depends on some details of how iOS handles audio sessions that I'm not sure about. What I think is likely happening is that text to speech package you're using is changing the audio mode and not remembering the current mode when they do. Basically speech_to_text puts the audio into play and record during a listen session. If the text to speech changes the mode to play only when it speaks and then either doesn't reset the mode at all or resets it back to a default instead of the pre-existing mode, you'd get the behaviour you describe. 

What I'm not sure about is if iOS will drop the active audio session when the audio mode is changed. If you can verify what the text to speech plugin is doing then we could at least test the theory.

**Comment by ab36245** [comment]
Thanks. That gives me something to look in to. I'll look at flutter_tts behavior and see if I can get some more information.

**Comment by dlutton** [comment]
@ab36245 I have updated the flutter_tts plugin so now the audio session is set to playAndRecord.

**Comment by ab36245** [comment]
That's great. Thanks!

**Comment by ab36245** [comment]
I've restested with flutter_tts 1.0.0 but still have the same problem. As soon as any audio output is generated with flutter_tts the speech_to_text listener (started *before* the audio output) does not appear to receive any input. I can only get the listener to work by stopping and restarting it.

**Comment by sowens-csd** [comment]
That's a shame, I was hoping for an easy solution. It seems like the audio session is getting disrupted by the playback. I'll add it to my list to look at. In the meantime I guess you will have to stop the listener while doing the speech playback and then restart it once the speech playback is done.

**Comment by ab36245** [comment]
Yes, that's probably my best option for the moment. However, in my limited testing so far, doing that tends to increase the chances of the problem I described in #65. Let me know if you want any help reproducing the issue.

**Comment by sowens-csd** [comment]
I'm going to close this one and focus on #65 if that's okay?
