### ISSUE TITLE
Errors like error_no_match and error_timeout don't get reset.

### ISSUE THREAD

**Issue by benzai10** [csdcorp/speech_to_text#67]
After an "error_timeout" has occurred, it happens that in one of the following listening phases a "error_timeout" or "error_no_match" gets triggered too quickly (you can see it displaying in the "Error Status" text field on the screen. I would expect that once the "error_timeout" has occurred, the next time the method "startListening" is triggered, the timeout is again set to 10 seconds (I tested with the example app). Often, the timeout happens after around 4 seconds.

Sometimes, the "error_no_match" is thrown almost instantly but this behavior is hard to replicate and occurs less often than the one with "error_timeout".

**Comment by sowens-csd** [comment]
error_timeout and error_no_match are from the underlying platform and are not controlled by the `listenFor` duration set on the listener. No error is triggered when the `listenFor` duration elapses. How either iOS or Android decides on when to throw those errors is OS and implementation specific and I don't seem to have any control over it. I've tried various parameters in the Android implementation but it seems to ignore them all. 

Given that there is no reset that happens after an error.

**Comment by benzai10** [comment]
Thank you for the quick answer! Since you have tried various parameters in the Android implementation do you maybe have a suggestion of possible workarounds? Maybe you can give me some inspirational hints.

**Comment by sowens-csd** [comment]
The error_no_match can be triggered by the recognizer trying to process its own start beep as speech, unfortunately. You can check this by turning the device volume down and seeing if you can reproduce it. I don't currently have any good way to avoid the error_timeout, so far all you can do is to process it and restart the listening session. I am exploring other possible workaround at the Android level. I have an open issue to investigate dictation mode, it may also be possible to support a long listening mode by handling some of the possible errors in the Android plugin implementation. I'd probably add a flag to the initialization to enable it so that you could choose the default platform behaviour or the work arounds. These are just experimental thoughts at this point though.
